config/routes.rb
Company::Application.routes.draw do
  root :to => "top#index"
  get "/access" => "access#index"
  get "/news" => "news#index"
  get "/about" => "about#index"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include Jpmobile::ViewSelector
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/about/index.html.erb
<h2>会社概要</h2>
<ul>
	<li>2011年3月設立</li>
</ul>

app/views/access/index.html.erb
<h2>アクセス</h2>
<p>
地下鉄北東線　中央５番出口を出て徒歩２分
</p>

app/views/layouts/_footer.html.erb
&copy; Company, inc. <%= Time.now.year -%>

app/views/layouts/_footer_mobile.html.erb
<div align="center">(c) Campany, inc, <%= Time.now.year -%></div>

app/views/layouts/_header.html.erb
<h1>Company</h1>

app/views/layouts/_header_mobile.html.erb
<div align="center">Company</div>

app/views/layouts/_menu.html.erb
<ul class="menu" data-role="listview">
	<li><%= link_to "トップページ", root_url -%></li>
	<li><%= link_to "会社概要", about_url -%></li>
	<li><%= link_to "ニュース", news_url -%></li>
	<li><%= link_to "アクセス", access_url -%></li>
</ul>

app/views/layouts/_menu_mobile.html.erb
&#xe6e2;<%= link_to "トップページ", root_url, { :accesskey => "1" } -%><br />
&#xe6e3;<%= link_to "会社概要", about_url, { :accesskey => "2" } -%><br />
&#xe6e4;<%= link_to "ニュース", news_url, { :accesskey => "3" } -%><br />
&#xe6e5;<%= link_to "アクセス", access_url, { :accesskey => "4" } -%><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Company</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
	  <%= render :partial => "layouts/header" -%>
  </div>
  <div id="wrapper">
	  <div id="menu">
		  <%= render :partial => "layouts/menu" -%>
	  </div>
	  <div id="contents"><%= yield %></div>
	  <div class="clear"></div>
  </div>
  <div id="footer">
	  <%= render :partial => "layouts/footer" -%>
  </div>
</body>
</html>

app/views/layouts/application_mobile.html.erb
<html>
	<head>
		<title>Company</title>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<%= render :partial => "layouts/header" -%>
		<%= yield %>
		<%= render :partial => "layouts/menu" -%>
		<%= render :partial => "layouts/footer" -%>
	</body>
</html>

app/views/news/index.html.erb
<h2>ニュースリリース</h2>
<ul>
	<li>2011年4月　ホームページを公開しました</li>
</ul>

app/views/top/index.html.erb
<h2>Companyのホームページ</h2>
<p>信頼と実績のプログラミング</p>